[package]
name = "loopybayesnet"
version = "0.1.0"
authors = ["Victor Berger <victor.berger@inria.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.12"
